# Generated by Django 4.1.1 on 2022-09-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborator',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
