# Generated by Django 4.1.1 on 2022-09-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_colaborator_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborator',
        ),
    ]
