# Generated by Django 4.1.1 on 2022-09-30 21:55

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0003_delete_colaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=portal.models.generate_digits, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('username',),
            },
        ),
    ]
