# Generated by Django 4.1.1 on 2022-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_colaborator_department_colaborator_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborator',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('cib', 'CIB'), ('bcc', 'BCC'), ('chnw', 'CHNW')], default='engineering', max_length=20),
        ),
    ]
