# Generated by Django 4.1.1 on 2022-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_colaborator_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborator',
            options={'ordering': ('first_name',)},
        ),
        migrations.AddField(
            model_name='colaborator',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
