# Generated by Django 4.1.1 on 2022-10-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_colaborator_options_colaborator_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaborator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
