# Generated by Django 4.1.1 on 2022-10-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_colaborator_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemToBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Item To Buy',
                'verbose_name_plural': 'Items To Buy',
                'ordering': ('item_name',),
            },
        ),
    ]
