# Generated by Django 4.1.1 on 2022-10-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_itemtobuy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemToBuy',
        ),
    ]
