# Generated by Django 4.1.1 on 2022-10-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_itemtobuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtobuy',
            name='category',
            field=models.CharField(choices=[('hygien', 'Hygien'), ('food', 'Food'), ('clothes', 'Clothes'), ('documents', 'Documents'), ('family', 'Family')], default='hygien', max_length=20),
        ),
    ]
