# Generated by Django 4.1.1 on 2022-10-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_itemtobuy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtobuy',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('moderate', 'Moderate'), ('low', 'Low')], default='critical', max_length=20),
        ),
    ]
