# Generated by Django 4.1.1 on 2022-10-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_itemtobuy_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtobuy',
            name='category',
            field=models.CharField(choices=[('hygien', 'Hygien'), ('food', 'Food'), ('clothes', 'Clothes'), ('documents', 'Documents'), ('family', 'Family'), ('debt', 'Debt'), ('house', 'House')], default='hygien', max_length=20),
        ),
    ]
