# Generated by Django 4.1.1 on 2022-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_itemtobuy_urgent_alter_itemtobuy_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('second_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operator', models.CharField(max_length=20)),
            ],
        ),
    ]
