# Generated by Django 4.1.1 on 2022-10-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_alter_calculator_first_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculator',
        ),
    ]
