# Generated by Django 4.1.1 on 2022-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_delete_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.FloatField()),
                ('second_number', models.FloatField()),
                ('operator', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calculation',
                'verbose_name_plural': 'Calculations',
            },
        ),
    ]
