# Generated by Django 4.1.1 on 2022-10-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude1', models.FloatField()),
                ('longetude1', models.FloatField()),
                ('latitude2', models.FloatField()),
                ('longetude2', models.FloatField()),
            ],
        ),
    ]
