# Generated by Django 4.1.1 on 2022-10-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.FloatField()),
                ('green', models.FloatField()),
                ('blue', models.FloatField()),
            ],
        ),
    ]
