# Generated by Django 4.1.1 on 2022-10-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_alter_color_blue_alter_color_green_alter_color_red'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
