# Generated by Django 4.1.1 on 2022-10-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('id',)},
        ),
    ]
