# Generated by Django 4.1.1 on 2022-10-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_alter_color_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
