# Generated by Django 4.1.1 on 2022-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtobuy',
            name='buy_from',
            field=models.CharField(choices=[('cabaz', 'Cabaz'), ('salary', 'Salary')], default='cabaz', max_length=20),
        ),
    ]
