# Generated by Django 4.1.1 on 2022-12-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_alter_itemtobuy_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtobuy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
